In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

Leitura do dataframe MICRODADOS_ENEM_2023

In [3]:
colunas = [
    'NU_INSCRICAO',

    #localização
    'SG_UF_PROVA',
    'NO_MUNICIPIO_PROVA',

    # perfil do aluno
    'TP_SEXO',
    'TP_COR_RACA',
    'TP_FAIXA_ETARIA',

    # escola
    'TP_ESCOLA',
    'TP_DEPENDENCIA_ADM_ESC',

    # renda
    'Q006',

    # notas
    'NU_NOTA_CN',
    'NU_NOTA_CH',
    'NU_NOTA_LC',
    'NU_NOTA_MT',
    'NU_NOTA_REDACAO',

    # presença
    'TP_PRESENCA_CN',
    'TP_PRESENCA_CH',
    'TP_PRESENCA_LC',
    'TP_PRESENCA_MT'
]

In [4]:
df = pd.read_csv(
    '../dados/microdados_enem_2023.csv',
    sep=';',
    encoding='latin-1',
    usecols=colunas
)

In [5]:
df.head()

,NU_INSCRICAO,TP_FAIXA_ETARIA,TP_SEXO,TP_COR_RACA,TP_ESCOLA,TP_DEPENDENCIA_ADM_ESC,NO_MUNICIPIO_PROVA,SG_UF_PROVA,TP_PRESENCA_CN,TP_PRESENCA_CH,TP_PRESENCA_LC,TP_PRESENCA_MT,NU_NOTA_CN,NU_NOTA_CH,NU_NOTA_LC,NU_NOTA_MT,NU_NOTA_REDACAO,Q006
0,210059085136,14,M,1,1,NaN,Brasília,DF,0,0,0,0,NaN,NaN,NaN,NaN,NaN,F
1,210059527735,12,M,1,1,NaN,Brasília,DF,0,0,0,0,NaN,NaN,NaN,NaN,NaN,H
2,210061103945,6,F,1,1,NaN,Caxias do Sul,RS,1,1,1,1,502.0,498.9,475.6,363.2,700.0,C
3,210060214087,2,F,3,2,2.0,Fortaleza,CE,1,1,1,1,459.0,508.5,507.2,466.7,880.0,C
4,210059980948,3,F,3,2,2.0,Quixadá,CE,1,1,1,1,402.5,379.2,446.9,338.3,560.0,B

In [6]:
df.shape

(3933955, 18)

Leitura do DataFrame ITENS_PROVA_2023

In [9]:
colunas_itens = [
    'SG_AREA',
    'CO_HABILIDADE',
    'IN_ITEM_ABAN',
    'NU_PARAM_A',
    'NU_PARAM_B',
    'NU_PARAM_C',
    'TX_COR'
]

In [10]:
df_itens = pd.read_csv(
    '../dados/ITENS_PROVA_2023.csv',
    sep=';',
    encoding='latin-1',
    usecols=colunas_itens
)

In [11]:
df_itens.head()

,SG_AREA,CO_HABILIDADE,IN_ITEM_ABAN,NU_PARAM_A,NU_PARAM_B,NU_PARAM_C,TX_COR
0,LC,14,0,2.20125,0.82582,0.21190,AMARELA
1,LC,23,0,2.43295,0.90091,0.13239,AMARELA
2,LC,26,0,1.95105,-0.13372,0.19557,AMARELA
3,LC,12,0,1.14733,0.38901,0.23027,ROSA
4,LC,8,0,2.25894,1.00728,0.17726,AMARELA

In [13]:
df_itens.shape

(5550, 7)